### ISSUE TITLE
Stable release tracker

### ISSUE THREAD

**Issue by unknownconstant** [unknownconstant/ArduinoBLE#11]
Thread to track issues relating to the implementation of BLE bonding and pairing when the Arduino is in peripheral mode.

Confirmation of testing against the following hardware:

### Arduino
- [x] Arduino iot 33
- [ ] Arduino iot BLE
- [ ] Arduino MKR WiFi 1010
- [ ] Arduino UNO WiFi Rev.2

### Central
- [x] iOS
- [x] Android
- [x] Windows
- [ ] MacOS
